-- This Script is Part of the Prometheus Obfuscator by Levno_710
--
-- config.lua
--
-- In this Script, some Global config Variables are defined
-- These may be changed

-- You are not allowed to change the following Variables
local VERSION = "Alpha v0.1";
local NAME    = "Prometheus";
local BY      = "Levno_710";

-- Config Starts here
return {
	Name = NAME,
	NameUpper = string.upper(NAME),
	NameAndVersion = string.format("%s %s", NAME, VERSION),
	Version = VERSION;
	Watermark = string.format("Obfuscated using %s %s by %s", NAME, VERSION, BY); -- You are not allowed to edit the watermark
	-- Config Starts Here
	IdentPrefix = "__prometheus_"; -- The Prefix used for Identifiers generated by PROMETHEUS. NOTE: There should be no identifiers in the script to be obfuscated starting with that prefix, because that can lead to weird bugs
	
	SPACE = " "; -- The Whitespace to be used by the unparser
	TAB   = "\t"; -- The Tab Whitespace to be used by the unparser for pretty printing
}