name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build and run tests
        run: bash scripts/run-tests.sh -b -n 10 --ci
